coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 2%
        minimum: 75%
    patch:
      default:
        target: 80%
        threshold: 2%
        minimum: 70%

  ignore:
    - "**/*.test.ts"
    - "**/*.config.ts"
    - "**/*.d.ts"
    - "coverage/**/*"

comment:
  layout: "header, diff, components, files, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  show_carryforward_flags: true
  hide_project_coverage: false
  hide_if_no_changes: false
