coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
    patch:
      default:
        target: auto
        threshold: 0%

  precision: 2
  round: down
  range: "70...100"

parsers:
  javascript:
    enable_partials: yes

comment:
  layout: "diff, files"
  behavior: default
  require_changes: false
  show_carryforward_flags: true

github_checks:
  annotations: true

fixes:
  - "::/"
