coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 5%
        minimum: 75%
        allow_decreases: true
    patch:
      default:
        target: 60%
        threshold: 5%
        minimum: 70%

  ignore:
    - "**/*.test.ts"
    - "**/*.config.ts"
    - "**/*.d.ts"
    - "coverage/**/*"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true
  hide_project_coverage: false
  hide_if_no_changes: true
