version: 2.1
orbs:
  cypress: cypress-io/cypress@3
workflows:
  build:
    jobs:
      - cypress/run:
          start-command: "npm run dev"
          wait-on-timeout: "60"
          command: "npm run cypress:run"
