version: 2.1
orbs:
  cypress: cypress-io/cypress@3
workflows:
  build:
    jobs:
      - cypress/run:
          build: "npm run build"
          start-command: "npm run dev"
          wait-on: "http://localhost:3000"
