version: 2.1
orbs:
  cypress: cypress-io/cypress@3
workflows:
  build:
    jobs:
      - cypress/run:
          command: npm run cypress:run
          install-command: npm ci
          start: npm run dev
          wait-on: "http://localhost:3000"
